### ISSUE TITLE
Missing Hashes of Weak Debian Key Modulus in Files

### ISSUE THREAD

**Issue by faiqq7** [CVE-2008-0166/dwk_blocklists#2]
There are several files in this repository (sha256_modulus_2048, sha256_modulus_3072, sha256_modulus_4096, and sha256_modulus_8192) that contain hashes of weak Debian key moduli. However, I noticed that these files do not include the hashes of moduli for some weak CSR (Certificate Signing Request) keys, which are provided by another website as samples. After double-checking with the [badkeys.info](https://badkeys.info/) database, I can confirm that these keys are indeed weak Debian keys.

Steps to Reproduce:

- Compare the hashes of modulus of CSR from [certlogik.com](https://certlogik.com/debian-weak-key-check/) and [bugzilla.mozilla.org](https://bugzilla.mozilla.org/show_bug.cgi?id=1620772) with the modulus hashes in the repository.
- Cross-reference them with the [badkeys.info](https://badkeys.info/) database to verify that they are weak Debian keys.
- Notice that the repository files are missing the hashes of these modulues.

**Comment by robstradling** [comment]
Hi @faiqq7.  Thanks for your interest.  I don't believe any modulus hashes are "missing" from this repository though.

> Compare the hashes of modulus of CSR from [certlogik.com](https://certlogik.com/debian-weak-key-check/)

The example CSR given on that page has an RSA-1024 key.  That **deprecated** RSA key length is not covered by this dwk_blocklists repository.  That's intentional, because the main purpose of the repositories under https://github.com/CVE-2008-0166 is to provide the WebPKI community with tooling to ensure compliance with CABForum ballot [SC-73](https://cabforum.org/2024/06/07/ballot-sc-73-compromised-and-weak-keys/) going forwards.

> and [bugzilla.mozilla.org](https://bugzilla.mozilla.org/show_bug.cgi?id=1620772) with the modulus hashes in the repository.

Actually, the modulus hash for the certificate cited in that Bugzilla incident **is present** in this dwk_blocklists repository, as https://crt.sh/?id=2531502044&opt=pkimetal demonstrates.  ([pkimetal](https://github.com/pkimetal/pkimetal) uses [dwklint](https://github.com/CVE-2008-0166/dwklint), which relies on this dwk_blocklists repository).  Steps to reproduce...

```bash
> curl --silent "https://crt.sh/?d=2531502044" | openssl x509 -modulus -noout | sed "s/Modulus=//g" | xxd -r -ps | sha256sum
0c6916a0fd684521a81a018f232915db335fe77e24e9908937b104d5b1fda9e0  -

> grep -n 0c6916a0fd684521a81a018f232915db335fe77e24e9908937b104d5b1fda9e0 sha256_modulus_2048.csv
14442:0c6916a0fd684521a81a018f232915db335fe77e24e9908937b104d5b1fda9e0
```

Also, just in case this is relevant to why you thought this hash was missing...

The first line of that modulus in the output from "openssl x509" is as follows:
00:f9:36:07:e7:b5:b3:4d:37:c0:44:d9:a8:fd:5c:

Note that the leading 0x00 byte is part of the DER encoding rather than part of the actual modulus value, so the 0x00 is not included in the hash calculation.

**Comment by faiqq7** [comment]
Hey @robstradling , I'm trying to check this CSR and I'm unable to find the hash of the modulus in sha256_modulus_2048.

```
-----BEGIN CERTIFICATE REQUEST-----
MIICiDCCAXACAQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUx
ITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDCCASAwDQYJKoZIhvcN
AQEBBQADggENADCCAQgCggEBANU56hG9cS5aDxgCCpncSVx7jWQInMI/yA40lrIb
IKp342EAh/B8kE/fpeEWJggQyv7rG6oKcOPs4eT4NGcfHZv4aPgda+c+Fb/aZOUi
4nnjPp8TNW312uaM/Eybs7SB8/C5kKdwcgGpfZHOB01wwjKGlgJhY7vpn5p6Rvqf
rfr3O9O7sySS6iMAqGaPyQg3S9/ivXx6HgpT/tTHltUp1sjfCK0Jl6jGKg4iMzCu
XJDIU1fIGveRu+w1v8WBnS6fiHOTmj36NWxPlTUnvNqEm8Gk3JjktoFy/Ufa7O9I
DRriUW7A71TNdy4yoS+Jr49QATh6smkemcm63TbvS1ZDXskCASOgADANBgkqhkiG
9w0BAQsFAAOCAQEAE2LTq/P0nsYLhgnrRLK6LJ/glXJnAyalkvGg+UsUZRkTS28H
zPkmZ044TlZP8LJKjjJxB/dhlmzt9VtvA7ee0IHQcK750VWHqU0FNZ6XSIZvyjhP
6TpfoPUeGLLOJ4wlIA5LXevUdAX7zapLfzbmHyU5C9x0Od35vjgeLx5Pw+31WREw
x47T0lylrfoTQSZuz+uRP48eBkbhTvqV7gBb2nijaK3lzah4fKKgXcieMNZdJXT+
kM+tqcyWBnzRlWcR5Qcq23+MvfKOsTU3Sl/ebmJV51nN70W189ptyx9Y2SXmPRmT
nFo1dUMmQNqUBXNhpn1+WBVKXVj/lz9G0Y7d/A==
-----END CERTIFICATE REQUEST-----
```

Could you confirm if the hash is present in the file? I suspect there may be an issue with the way I'm computing the hash.

Thanks!

**Comment by robstradling** [comment]
Hi @faiqq7.  Feeding that key into https://badkeys.info/ led me to the corresponding private key at https://github.com/badkeys/debianopenssl/blob/main/rsa2048/ssh/le32/23747.key.  Notice the "ssh", which indicates that this key was generated by a version of OpenSSH vulnerable to CVE-2008-0166.

This dwk_blocklists repository only covers weak keys generated by vulnerable versions of OpenSSL.  Again, this is intentional, because the main purpose of the repositories under https://github.com/CVE-2008-0166 is to provide the WebPKI community with tooling to ensure compliance with CABForum ballot [SC-73](https://cabforum.org/2024/06/07/ballot-sc-73-compromised-and-weak-keys/) going forwards.

**Comment by robstradling** [comment]
By the way, if you happen to be interested in checking X.509 certificates for public keys that are vulnerable to CVE-2008-0166, you might be interested in https://github.com/pkimetal/pkimetal, which integrates both https://github.com/badkeys/badkeys and https://github.com/CVE-2008-0166/dwklint.
